"""Record source-verified benchmark candidates without constructing model inputs."""
from pathlib import Path
import csv,json
R=Path(__file__).resolve().parents[1];D=R/'results/study-package';D.mkdir(parents=True,exist_ok=True)
source='https://pmc.ncbi.nlm.nih.gov/articles/PMC8672774/table/tab2/'
raw=[('MP-1687','Parent', '=',60),('5','Pro6Ala','>',48080),('6','Leu7Ala','>',48080),('7','Tyr8Ala','=',691),('8','Ile9Ala','>',48080),('9','Ser10Ala','=',1072),('10','Tyr11Ala','=',2430),('11','Asp12Ala','>',48080),('12','Pro13Ala','=',427),('13','Val14Ala','=',161)]
rows=[{'source_compound_id':name,'parent':'MP-1687','source_modification':mod,'target':'KRAS G12D','nucleotide':'GDP','assay':'TR-FRET','endpoint':'EC50','relation':rel,'value_nM':value,'source_table':'Lim et al. 2021 Table 2','source_url':source,'chemistry_family':'D-Cys thioacetal modified peptide; not original KRpep-2d','model_input_ready':False,'inference_performed':False} for name,mod,rel,value in raw]
with (D/'experimental-control-candidates.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
claims=[
 ('Target','KRAS4B G12D 1-169 with GDP, matched to 5XCO','results/target/target-qc.json','Coordinate-derived construct and pocket','The reference is experimental; no novel design is implied.'),
 ('Published affinity','KRpep-2d GDP SPR KD 8.9 nM G12D, 58 nM WT','https://pmc.ncbi.nlm.nih.gov/articles/PMC5512123/table/tbl1/','Published assay-specific values','Do not relabel IC50 as KD or imply these values were measured by this campaign.'),
 ('Control chemistry','Original control is capped disulfide peptide; modified MP series has different stereochemistry and linker','https://pmc.ncbi.nlm.nih.gov/articles/PMC8672774/','Distinct molecules and assay context','Cis D-Cys5-Pro6 and D-Arg changes belong to specified MP derivatives.'),
 ('Sequence model','ESMC masked-residue calculations completed','results/esm/metadata.json','Sequence-model technical checks','Not pocket affinity, hotspot experimental validation or mutant selectivity.'),
 ('First calibration','V1 separation failed','results/controls/gate-summary.json','Observed within-v1 positive-minus-scramble gap','V1 remains failed and its post-run geometry findings are diagnostics.'),
 ('Second calibration','V2 chemistry passed; separation failed','results/control-remediation-v2-002/analysis/gate-summary.json','Declared chemical checks and within-v2 confidence gap','No absolute confidence comparison across different tokenizations.'),
 ('Sample size','12 predictions of 2 control identities across 2 representations','results/controls/per-seed.csv; results/control-remediation-v2-002/analysis/per-seed.csv','Model sampling replicates','Not 12 independent peptides, experiments or biological replicates.'),
 ('New benchmark candidates','10 reported MP-1687 series assay entries including parent','https://pmc.ncbi.nlm.nih.gov/articles/PMC8672774/table/tab2/','Curated experimental EC50 values and greater-than bounds','These are literature entries, not new predictions; exact noncanonical structures require verification.'),
 ('Training dependence','Published peptide-docking benchmark reports training bias and high-confidence incorrect poses','https://pmc.ncbi.nlm.nih.gov/articles/PMC12518507/','Context for independent pose validation','Does not diagnose the mechanism of this campaign failure.'),
 ('Recent cyclic benchmark','2026 preprint separates pose generation and ranking limitations','https://www.biorxiv.org/content/10.64898/2026.08.20.746104v1.full','Relevant, explicitly unreviewed context','Known-complex pose benchmark; not evidence of experimental binder classification.'),
 ('Discovery outcome','No selected novel peptide or WT counter-screen result','CAMPAIGN_STATE.json','Candidate pipeline stopped by recorded gates','No efficacy, potency, developability or assay-draft claim for unselected designs.'),
 ('Reproduction','Offline exported-data rebuild and hashes verified in tested environment','results/reproducibility-qc.json','Reproduction of saved calculations','Does not reproduce neural inference or guarantee cross-platform byte identity.')]
(D/'evidence-matrix.json').write_text(json.dumps([dict(zip(['topic','claim','evidence','permitted_interpretation','limitation'],x)) for x in claims],indent=2)+'\n')
(D/'control-readiness.json').write_text(json.dumps({'reviewed_on':'2026-09-14','source':source,'entries':len(rows),'new_prediction_count':0,'decision':'NO_NEW_INFERENCE_READY','reasons':['Original scramble has no experimentally established inactive label.','The new table is a distinct noncanonical thioacetal family; exact structure and stereochemistry have not been independently instantiated.','TR-FRET EC50 and right-censored values cannot be treated as peptide binding KD.','A small panel and three seeds do not validate a general binder classifier.'],'next_requirements':['Verify exact chemical structures against primary figures/supplementary material.','Check supported model representation and define an independent benchmark before inference.','Confirm deadline and current free compute allowance.']},indent=2)+'\n')
print('Curated 10 literature entries and 12 claim/evidence records; no predictions or model inputs created.')
